<?PHP
session_start();
$con=mysqli_connect("localhost","root","1234") or die("error in connect".mysqli_error($con));
$db=mysqli_select_db($con,"sport") or die("error in db selection".mysqli_error($con));
echo"<style>";
echo"#pro{font-family: \"Trebuchet MS\", Arial, Helvetica, sans-serif;border-collapse: collapse;width: 100%;}";
echo"#pro td, #pro th {border: 1px solid #ddd;padding: 8px;}";
echo"#pro tr:nth-child(even){background-color: #f2f2f2;}";
echo"#pro tr:hover {background-color: #ddd;}";
echo"#pro th {padding-top: 12px;padding-bottom: 12px;text-align: left;background-color: #009999;color: white;}";
echo"input[type=\"submit\"],input[type=\"reset\"]{background-color: #009999;color: white;padding: 16px 20px;margin: 8px 0;border: none;cursor: pointer;width: 15%;opacity: 0.9;}";
echo"input[type=\"submit\"],input[type=\"reset\"]:hover {opacity: 1;}";
echo"</style>";
$tid=$_POST['tid'];
$tcid=$_POST['tcid'];
$q="Select * from tour where t_id='$tid'";
$x=mysqli_query($con,$q) or die("error in selecting data".mysqli_error($con));
$row=mysqli_fetch_array($x);
echo"<h1 align=\"center\">$row[4]</h1>";
echo "<table id=\"pro\" align=\"center\" border=1>";
echo"<tr><th>Sport</th><th>Gender</th><th>MaxTeams</th><th>City</th><th>Address</th></tr>";
echo"<tr><td>$row[2]</td><td>$row[5]</td><td>$row[12]</td><td>$row[3]</td><td>$row[10]</td></tr>";
echo"</table>";
echo"<br>";
echo"<table id=\"pro\" align=\"center\" border=1>";
echo"<tr><th>Reg start</th><th>Reg end</th><th>Start</th><th>End</th></tr>";
echo"<tr><td>$row[6]</td><td>$row[7]</td><td>$row[8]</td><td>$row[9]</td></tr>";
echo"</table>";
$q="Select * from tour_creator where tc_id='$tcid'";
$x=mysqli_query($con,$q) or die("error in selecting data".mysqli_error($con));
$row=mysqli_fetch_array($x);
echo"<h1 align=\"center\">Tournament Creator</h1>";
echo "<table id=\"pro\" align=\"center\" border=1>";
echo"<tr><th>First name</th><th>Last name</th><th>Phone Number</th><th>Email</th><th>State</th><</tr>";
echo"<tr><td>$row[3]</td><td>$row[5]</td><td>$row[7]</td><td>$row[8]</td><td>$row[10]</td></tr>";
echo"</table>";
echo"<form align=\"center\"  method=\"POST\" action=\"adm_approve_tour.php\"> <input type=\"hidden\" name=\"det\" value=\"$tid\"> <input name=\"choice\"  type=\"submit\" value=\"Approve\">  <input name=\"choice\" type=\"submit\" value=\"Reject\"></form>";
