<?PHP
session_start();
$con=mysqli_connect("localhost","root","1234") or die("error in connect".mysqli_error($con));
$db=mysqli_select_db($con,"sport") or die("error in db selection".mysqli_error($con));
echo"<style>";
echo"#pro{font-family: \"Trebuchet MS\", Arial, Helvetica, sans-serif;border-collapse: collapse;width: 100%;}";
echo"#pro td, #pro th {border: 1px solid #ddd;padding: 8px;}";
echo"#pro tr:nth-child(even){background-color: #f2f2f2;}";
echo"#pro tr:hover {background-color: #ddd;}";
echo"#pro th {padding-top: 12px;padding-bottom: 12px;text-align: left;background-color: #6666ff;color: white;}";
echo"input[type=\"submit\"],input[type=\"reset\"]{background-color: #6666ff;color: white;padding: 16px 20px;margin: 8px 0;border: none;cursor: pointer;width: 15%;opacity: 0.9;}";
echo"input[type=\"submit\"],input[type=\"reset\"]:hover {opacity: 1;}";
echo"input[type=text], input[type=password],input[type=number] {width: 30%;padding: 15px;margin: 5px 0 22px 0;display: inline-block;border: none;background: #f1f1f1;}";
echo"</style>";
$y=$_SESSION["ID"];
$tid=$_POST['det'];
$q="Select * from tour where t_id='$tid'";
$recs=mysqli_query($con,$q) or die("error in selecting data".mysqli_error($con));
$row=mysqli_fetch_array($recs);
$tid=$row[0];
echo"<h1 align=\"center\">$row[4]</h1>";
echo"<br>";
echo "<table id=\"pro\" align=\"center\" border=1>";
echo"<tr><th>Sport</th><th>Gender</th><th>City</th><th>Address</th><th>Status</th><</tr>";
echo"<tr><td>$row[2]</td><td>$row[5]</td><td>$row[3]</td><td>$row[10]</td><td>$row[11]</td></tr>";
echo"</table>";
echo"<br><br>";
$q="Select * from tour_creator where tc_id='$row[1]'";
$recs=mysqli_query($con,$q) or die("error in selecting data".mysqli_error($con));
$row=mysqli_fetch_array($recs);
echo"<h1 align=\"center\">Tournament Creator</h1>";
echo "<table id=\"pro\" align=\"center\" border=1>";
echo"<tr><th>First name</th><th>Last name</th><th>Phone Number</th><th>Email</th><th>State</th><</tr>";
echo"<tr><td>$row[3]</td><td>$row[5]</td><td>$row[7]</td><td>$row[8]</td><td>$row[10]</td></tr>";
echo"</table>";
echo"<br><br>";
echo"<form align=\"center\"  method=\"POST\" action=\"S_reg_tour.php\"> <input type=\"hidden\" name=\"det\" value=\"$tid\">Enter Team name<br> <input type=\"text\" name=\"Team\" required><br><input  type=\"submit\" value=\"Register\"></form>";